### ISSUE TITLE
Support for UDP protocol

### ISSUE THREAD

**Issue by misterquestions** [pawelgaczynski/gain#3]
Hey there,

This library seems very promissing for me.

Wondering if there are any plans on adding the UDP protocol support, aswell as more documentation around on how to use it.

**Comment by pawelgaczynski** [comment]
Hi,

The answer to both questions is: yes. I am currently working on improving the buffers and API. When I finish it I will create documentation and more usage examples. Then I will write support for the UDP protocol. Could you tell me what is your use case for Gain?

**Comment by misterquestions** [comment]
Well, basically I’m developing a game server where I’d love to use Go instead of C++ or Rust but achieving the best performance possible

**Comment by pawelgaczynski** [comment]
@misterquestions support for the UDP protocol has been implemented.
